kafka:
  persistence:
    size: 1Gi
  controller:
    replicaCount: 1
    logPersistence:
      size: 1Gi
    persistence:
      size: 1Gi
    resources:
      requests:
        memory: "1536Mi"
        cpu: "400m"
      limits:
        memory: "1536Mi"
        cpu: "400m"
  extraConfig: |
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1

mysql:
  architecture: "replication"
  auth:
    rootPassword: "rootPassword12"
    replicationUser: "repl_user"
    replicationPassword: "repl_password"
  primary:
    persistence:
      enabled: true
      size: 1Gi
    resources:
      requests:
        memory: "736Mi"
        cpu: "250m"
      limits:
        memory: "836Mi"
        cpu: "300m"
  secondary:
    replicaCount: 1
    persistence:
      enabled: true
      size: 1Gi
    resources:
      requests:
        memory: "736Mi"
        cpu: "250m"
      limits:
        memory: "836Mi"
        cpu: "300m"
  initdbScripts:
    my_init_script.sh: |
      #!/bin/sh
      if [[ $(hostname) == *primary* ]]; then
        echo "Primary node"
        mysql -P 3306 -uroot -prootPassword12 -e "create database if not exists cgs_announcements";
        mysql -P 3306 -uroot -prootPassword12 -e "create database if not exists cgs_messages";
        mysql -P 3306 -uroot -prootPassword12 -e "create database if not exists cgs_orders";
        mysql -P 3306 -uroot -prootPassword12 -e "create database if not exists cgs_users";
      else
        echo "No primary node"
      fi

redis:
  architecture: standalone
  auth:
    enabled: false