spring:
  jpa:
    show-sql: true
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: update

  datasource:
    driver_class_name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/cgs_users"
    username: "salesUser"
    password: "consoleGameSales334"
