spring:
  profiles:
    active: jpa
  data:
    redis:
      port: 6379
      host: localhost
      timeout: 5000
      repositories:
        enabled: false
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: localhost:29092
    consumer:
      group-id: orderServiceGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.headers: false
        spring:
          json:
            trusted:
              packages: "edu/ubb/consolegamesales/backend/dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafkaOrderListOfUserReqTopic: orders-request-topic
kafkaOrdersListAnnouncementsReq: orders-announcements-request-topic
kafkaOrderDataReqConsumeTopic: order-request-topic
kafkaOrderAnnouncementReqProduceTopic: order-announcement-request-topic
kafkaOrderResponseProduceTopic: order-response-topic

kafkaOrderTransactionOrderCreateConsumeTopic: order-transaction-create-order-req-topic
kafkaOrderTransactionOrderCreateProduceTopic: order-transaction-create-order-resp-topic

kafkaOrderTransactionOrderDeleteConsumeTopic: order-transaction-delete-order-req-topic
kafkaOrderTransactionOrderDeleteProduceTopic: order-transaction-delete-order-resp-topic

server:
  port: 8083

jwtSecret: 2cdc5639dae1c27de9a074386c5dc8f526fc6c77921d4d34e07a1fceb7cfb9fb