# contains a deployment, a service and a hpa for the announcement service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pn-deployment-ann
  labels:
    owner: pn
    app: kubernetes-cgs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pn-announc-serv
  template:
    metadata:
      labels:
        app: pn-announc-serv
    spec:
      containers:
        - name: kubernetes-cgs-announc
          image: micpn.azurecr.io/announcementservice:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: redis-host
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-redis
                  key: redis-password
            - name: KAFKA_SERVER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: kafka-server
            - name: KAFKA_SECURITY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: kafka-security-protocol
            - name: KAFKA_PASSWD
              valueFrom:
                secretKeyRef:
                  name: my-kafka-user-passwords
                  key: client-passwords
            - name: CORS_ALLOWED_ORIGIN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: cors-allowed-origin
            - name: DB_URL_ANN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-url-ann
            - name: DB_User
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-password
          ports:
            - containerPort: 8082
              protocol: TCP
      imagePullSecrets:
        - name: registry-secret


---
apiVersion: v1
kind: Service
metadata:
  name: pn-service-ann
  labels:
    owner: pn
spec:
  ports:
    - name: http
      port: 8082
      protocol: TCP
  selector:
    app: pn-announc-serv

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-autoscaler-ann
  labels:
    owner: pn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pn-deployment-ann
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60