persistence:
  size: 1Gi
controller:
  replicaCount: 1
  logPersistence:
    size: 1Gi
  persistence:
    size: 1Gi
  resources:
    requests:
      memory: "1536Mi"
      cpu: "400m"
    limits:
      memory: "1536Mi"
      cpu: "400m"
extraConfig: |
  offsets.topic.replication.factor=1
  transaction.state.log.replication.factor=1