spring:
  jpa:
    show-sql: true
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: update

  datasource:
    driver_class_name: "com.mysql.cj.jdbc.Driver"
    url: ${DB_URL_MESS:jdbc:mysql://localhost:3306/cgs_messages}
    username: ${DB_User:salesUser}
    password: ${DB_PASSWORD:consoleGameSales334}
