spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update

  datasource:
    driver_class_name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/console_game_sales?allowPublicKeyRetrieval=true&useSSL=false"
    username: "salesUser"
    password: "consoleGameSales334"
